<?php
return array(
	['gameID' => 1, 'game' => 'I', 'date' => 'Jan. 15, 1967', 'stadium' => 'Los Angeles Memorial Coliseum', 'winner' => 'Green Bay', 'winScore' => 35, 'loser' => 'Kansas City', 'loseScore' => 10],
	['gameID' => 2, 'game' => 'II', 'date' => 'Jan. 14, 1968', 'stadium' => 'Orange Bowl (Miami)', 'winner' => 'Green Bay', 'winScore' => 33, 'loser' => 'Oakland', 'loseScore' => 14],
	['gameID' => 3, 'game' => 'III', 'date' => 'Jan. 12, 1969', 'stadium' => 'Orange Bowl (Miami)', 'winner' => 'New York Jets', 'winScore' => 16, 'loser' => 'Baltimore', 'loseScore' => 7],
	['gameID' => 4, 'game' => ' IV', 'date' => 'Jan. 11, 1970', 'stadium' => 'Tulane Stadium (New Orleans)', 'winner' => 'Kansas City', 'winScore' => 23, 'loser' => 'Minnesota', 'loseScore' => 7],
	['gameID' => 5, 'game' => ' V', 'date' => 'Jan. 17, 1971', 'stadium' => 'Orange Bowl (Miami)', 'winner' => 'Baltimore', 'winScore' => 16, 'loser' => 'Dallas', 'loseScore' => 13],
	['gameID' => 6, 'game' => ' VI', 'date' => 'Jan. 16, 1972', 'stadium' => 'Tulane Stadium (New Orleans)', 'winner' => 'Dallas', 'winScore' => 24, 'loser' => 'Miami', 'loseScore' => 3],
	['gameID' => 7, 'game' => ' VII', 'date' => 'Jan. 14, 1973', 'stadium' => 'Los Angeles Memorial Coliseum', 'winner' => 'Miami', 'winScore' => 14, 'loser' => 'Washington', 'loseScore' => 7],
	['gameID' => 8, 'game' => ' VIII', 'date' => 'Jan. 13, 1974', 'stadium' => 'Rice Stadium (Houston)', 'winner' => 'Miami', 'winScore' => 24, 'loser' => 'Minnesota', 'loseScore' => 7],
	['gameID' => 9, 'game' => ' IX', 'date' => 'Jan. 12, 1975', 'stadium' => 'Tulane Stadium (New Orleans)', 'winner' => 'Pittsburgh', 'winScore' => 16, 'loser' => 'Minnesota', 'loseScore' => 6],
	['gameID' => 10, 'game' => ' X', 'date' => 'Jan. 18, 1976', 'stadium' => 'Orange Bowl (Miami)', 'winner' => 'Pittsburgh', 'winScore' => 21, 'loser' => 'Dallas', 'loseScore' => 17],
	['gameID' => 11, 'game' => ' XI', 'date' => 'Jan. 9, 1977', 'stadium' => 'Rose Bowl (Pasadena, Calif.)', 'winner' => 'Oakland', 'winScore' => 32, 'loser' => 'Minnesota', 'loseScore' => 14],
	['gameID' => 12, 'game' => ' XII', 'date' => 'Jan. 15, 1978', 'stadium' => 'Superdome (New Orleans)', 'winner' => 'Dallas', 'winScore' => 27, 'loser' => 'Denver', 'loseScore' => 10],
	['gameID' => 13, 'game' => ' XIII', 'date' => 'Jan. 21, 1979', 'stadium' => 'Orange Bowl (Miami)', 'winner' => 'Pittsburgh', 'winScore' => 35, 'loser' => 'Dallas', 'loseScore' => 31],
	['gameID' => 14, 'game' => ' XIV', 'date' => 'Jan. 20, 1980', 'stadium' => 'Rose Bowl (Pasadena, Calif.)', 'winner' => 'Pittsburgh', 'winScore' => 31, 'loser' => 'Los Angeles', 'loseScore' => 19],
	['gameID' => 15, 'game' => ' XV', 'date' => 'Jan. 25, 1981', 'stadium' => 'Superdome (New Orleans)', 'winner' => 'Oakland', 'winScore' => 27, 'loser' => 'Philadelphia', 'loseScore' => 10],
	['gameID' => 16, 'game' => ' XVI', 'date' => 'Jan. 24, 1982', 'stadium' => 'Silverdome (Pontiac, Mich.)', 'winner' => 'San Francisco', 'winScore' => 26, 'loser' => 'Cincinnati', 'loseScore' => 21],
	['gameID' => 17, 'game' => ' XVII', 'date' => 'Jan. 30, 1983', 'stadium' => 'Rose Bowl (Pasadena, Calif.)', 'winner' => 'Washington', 'winScore' => 27, 'loser' => 'Miami', 'loseScore' => 17],
	['gameID' => 18, 'game' => ' XVIII', 'date' => 'Jan. 22, 1984', 'stadium' => 'Tampa (Fla.) Stadium', 'winner' => 'Los Angeles', 'winScore' => 38, 'loser' => 'Washington', 'loseScore' => 9],
	['gameID' => 19, 'game' => ' XIX', 'date' => 'Jan. 20, 1985', 'stadium' => 'Stanford (Calif.) Stadium', 'winner' => 'San Francisco', 'winScore' => 38, 'loser' => 'Miami', 'loseScore' => 16],
	['gameID' => 20, 'game' => ' XX', 'date' => 'Jan. 26, 1986', 'stadium' => 'Superdome (New Orleans)', 'winner' => 'Chicago', 'winScore' => 46, 'loser' => 'New England', 'loseScore' => 10],
	['gameID' => 21, 'game' => ' XXI', 'date' => 'Jan. 25, 1987', 'stadium' => 'Rose Bowl (Pasadena, Calif.)', 'winner' => 'New York Giants', 'winScore' => 39, 'loser' => 'Denver', 'loseScore' => 20],
	['gameID' => 22, 'game' => ' XXII', 'date' => 'Jan. 31, 1988', 'stadium' => 'Jack Murphy Stadium (San Diego)', 'winner' => 'Washington', 'winScore' => 42, 'loser' => 'Denver', 'loseScore' => 10],
	['gameID' => 23, 'game' => ' XXIII', 'date' => 'Jan. 22, 1989', 'stadium' => 'Joe Robbie Stadium (Miami)', 'winner' => 'San Francisco', 'winScore' => 20, 'loser' => 'Cincinnati', 'loseScore' => 16],
	['gameID' => 24, 'game' => ' XXIV', 'date' => 'Jan. 28, 1990', 'stadium' => 'Superdome (New Orleans)', 'winner' => 'San Francisco', 'winScore' => 55, 'loser' => 'Denver', 'loseScore' => 10],
	['gameID' => 25, 'game' => ' XXV', 'date' => 'Jan. 27, 1991', 'stadium' => 'Tampa (Fla.) Stadium', 'winner' => 'New York Giants', 'winScore' => 20, 'loser' => 'Buffalo', 'loseScore' => 19],
	['gameID' => 26, 'game' => ' XXVI', 'date' => 'Jan. 26, 1992', 'stadium' => 'Metrodome (Minneapolis)', 'winner' => 'Washington', 'winScore' => 37, 'loser' => 'Buffalo', 'loseScore' => 24],
	['gameID' => 27, 'game' => ' XXVII', 'date' => 'Jan. 31, 1993', 'stadium' => 'Rose Bowl (Pasadena, Calif.)', 'winner' => 'Dallas', 'winScore' => 52, 'loser' => 'Buffalo', 'loseScore' => 17],
	['gameID' => 28, 'game' => ' XXVIII', 'date' => 'Jan. 30, 1994', 'stadium' => 'Georgia Dome (Atlanta)', 'winner' => 'Dallas', 'winScore' => 30, 'loser' => 'Buffalo', 'loseScore' => 13],
	['gameID' => 29, 'game' => ' XXIX', 'date' => 'Jan. 29, 1995', 'stadium' => 'Joe Robbie Stadium (Miami)', 'winner' => 'San Francisco', 'winScore' => 49, 'loser' => 'San Diego', 'loseScore' => 26],
	['gameID' => 30, 'game' => ' XXX', 'date' => 'Jan. 28, 1996', 'stadium' => 'Sun Devil Stadium (Tempe, Ariz.)', 'winner' => 'Dallas', 'winScore' => 27, 'loser' => 'Pittsburgh', 'loseScore' => 17],
	['gameID' => 31, 'game' => ' XXXI', 'date' => 'Jan. 26, 1997', 'stadium' => 'Superdome (New Orleans)', 'winner' => 'Green Bay', 'winScore' => 35, 'loser' => 'New England', 'loseScore' => 21],
	['gameID' => 32, 'game' => ' XXXII', 'date' => 'Jan. 25, 1998', 'stadium' => 'Qualcomm Stadium (San Diego)', 'winner' => 'Denver', 'winScore' => 31, 'loser' => 'Green Bay', 'loseScore' => 24],
	['gameID' => 33, 'game' => ' XXXIII', 'date' => 'Jan. 31, 1999', 'stadium' => 'Pro Player Stadium (Miami)', 'winner' => 'Denver', 'winScore' => 34, 'loser' => 'Atlanta', 'loseScore' => 19],
	['gameID' => 34, 'game' => ' XXXIV', 'date' => 'Jan. 30, 2000', 'stadium' => 'Georgia Dome (Atlanta)', 'winner' => 'St. Louis', 'winScore' => 23, 'loser' => 'Tennessee', 'loseScore' => 16],
	['gameID' => 35, 'game' => ' XXXV', 'date' => 'Jan. 28, 2001', 'stadium' => 'Raymond James Stadium (Tampa, Fla.)', 'winner' => 'Baltimore', 'winScore' => 34, 'loser' => 'New York Giants', 'loseScore' => 7],
	['gameID' => 36, 'game' => ' XXXVI', 'date' => 'Feb. 3, 2002', 'stadium' => 'Superdome (New Orleans)', 'winner' => 'New England', 'winScore' => 20, 'loser' => 'St. Louis', 'loseScore' => 17],
	['gameID' => 37, 'game' => ' XXXVII', 'date' => 'Jan. 26, 2003', 'stadium' => 'Qualcomm Stadium (San Diego)', 'winner' => 'Tampa Bay', 'winScore' => 48, 'loser' => 'Oakland', 'loseScore' => 21],
	['gameID' => 38, 'game' => ' XXXVIII', 'date' => 'Feb. 1, 2004', 'stadium' => 'Reliant Stadium (Houston)', 'winner' => 'New England', 'winScore' => 32, 'loser' => 'Carolina', 'loseScore' => 29],
	['gameID' => 39, 'game' => ' XXXIX', 'date' => 'Feb. 6, 2005', 'stadium' => 'Alltel Stadium (Jacksonville, Fla.)', 'winner' => 'New England', 'winScore' => 24, 'loser' => 'Philadelphia', 'loseScore' => 21],
	['gameID' => 40, 'game' => ' XL', 'date' => 'Feb. 5, 2006', 'stadium' => 'Ford Field (Detroit)', 'winner' => 'Pittsburgh', 'winScore' => 21, 'loser' => 'Seattle', 'loseScore' => 10],
	['gameID' => 41, 'game' => ' XLI', 'date' => 'Feb. 4, 2007', 'stadium' => 'Dolphin Stadium (Miami)', 'winner' => 'Indianapolis', 'winScore' => 29, 'loser' => 'Chicago', 'loseScore' => 17],
	['gameID' => 42, 'game' => ' XLII', 'date' => 'Feb. 3, 2008', 'stadium' => 'University of Phoenix Stadium (Glendale, Ariz.)', 'winner' => 'New York Giants', 'winScore' => 17, 'loser' => 'New England', 'loseScore' => 14],
	['gameID' => 43, 'game' => ' XLIII', 'date' => 'Feb. 1, 2009', 'stadium' => 'Raymond James Stadium (Tampa, Fla.)', 'winner' => 'Pittsburgh Steelers', 'winScore' => 27, 'loser' => 'Arizona Cardinals', 'loseScore' => 23],
	['gameID' => 44, 'game' => ' XLIV', 'date' => 'Feb. 7, 2010', 'stadium' => 'Sun Life Stadium (Miami)', 'winner' => 'New Orleans Saints', 'winScore' => 31, 'loser' => 'Indianapolis Colts', 'loseScore' => 17],
	['gameID' => 45, 'game' => ' XLV', 'date' => 'Feb. 6, 2011', 'stadium' => 'Cowboys Stadium (Arlington, Texas)', 'winner' => 'Green Bay Packers', 'winScore' => 31, 'loser' => 'Pittsburgh Steelers', 'loseScore' => 25],
	['gameID' => 46, 'game' => ' XLVI', 'date' => 'Feb. 5, 2012', 'stadium' => 'Lucas Oil Stadium (Indianapolis)', 'winner' => 'New York Giants', 'winScore' => 21, 'loser' => 'New England Patriots', 'loseScore' => 17],
	['gameID' => 47, 'game' => ' XLVII', 'date' => 'Feb. 3, 2013', 'stadium' => 'Mercedes-Benz Superdome (New Orleans)', 'winner' => 'Baltimore Ravens', 'winScore' => 34, 'loser' => 'San Francisco 49ers', 'loseScore' => 31],
	['gameID' => 48, 'game' => ' XLVIII', 'date' => 'Feb. 2, 2014', 'stadium' => 'MetLife Stadium (East Rutherford, N.J.)', 'winner' => 'Seattle Seahawks', 'winScore' => 43, 'loser' => 'Denver Broncos', 'loseScore' => 8],
	['gameID' => 49, 'game' => ' XLIX', 'date' => 'Feb. 1, 2015', 'stadium' => 'University of Phoenix Stadium (Glendale, Ariz.)', 'winner' => 'New England Patriots', 'winScore' => 28, 'loser' => 'Seattle Seahawks', 'loseScore' => 24]
);