<?php //@ARGS context ?>
<div class="row">
	<div id="gameSchedules" class="col-sm-3">
		<div class="feedPanel">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu dui eu eros faucibus auctor. Pellentesque et nisi dignissim, cursus magna vitae, hendrerit est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi placerat cursus arcu, in viverra dui congue sed.
		</div>
		<div class="feedPanel">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu dui eu eros faucibus auctor. Pellentesque et nisi dignissim, cursus magna vitae, hendrerit est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi placerat cursus arcu, in viverra dui congue sed.
		</div>
		<div class="feedPanel">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu dui eu eros faucibus auctor. Pellentesque et nisi dignissim, cursus magna vitae, hendrerit est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi placerat cursus arcu, in viverra dui congue sed.
		</div>
	</div>
	<div id="articles" class="col-sm-5">
		<article>
			<div class="photoBox">
				<img src="{==$context->getAssetRoot()=}/img/ap-giants-panthers-football-4_3.jpg" alt="Giants vs Panthers game">
			</div>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu dui eu eros faucibus auctor. Pellentesque et nisi dignissim, cursus magna vitae, hendrerit est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi placerat cursus arcu, in viverra dui congue sed.
		</article>
	</div>
	<div id="newsSnippets" class="col-sm-4">
		<div class="feedPanel">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu dui eu eros faucibus auctor. Pellentesque et nisi dignissim, cursus magna vitae, hendrerit est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi placerat cursus arcu, in viverra dui congue sed.
		</div>
		<div class="feedPanel">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu dui eu eros faucibus auctor. Pellentesque et nisi dignissim, cursus magna vitae, hendrerit est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi placerat cursus arcu, in viverra dui congue sed.
		</div>
		<div class="feedPanel">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu dui eu eros faucibus auctor. Pellentesque et nisi dignissim, cursus magna vitae, hendrerit est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi placerat cursus arcu, in viverra dui congue sed.
		</div>
	</div>
</div>